# Copyright (c) 2021 Blacknon. All rights reserved.
# Use of this source code is governed by an MIT license
# that can be found in the LICENSE file.
# reference:
#   - https://motemen.hatenablog.com/entry/2019/11/github-actions-crossbuild-rust
#     - https://github.com/motemen/lssh/blob/97d3745dcc8931a1d75217573d5ca60705be632f/.github/workflows/release.yml
#   - https://github.com/greymd/teip/blob/master/.github/workflows/release.yml


name: Build Test Job.

on:
  push:
    branches:
      # - "topic/*"
      - "develop"

jobs:
  # build rust binary
  build:
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            os: ubuntu-latest
            ext: tar.gz
          # - goos: linux
          #   goarch: amd64
          #   os: ubuntu-latest
          #   ext: rpm
          # - goos: linux
          #   goarch: amd64
          #   os: ubuntu-latest
          #   ext: deb
          - goos: darwin
            goarch: amd64
            os: macos-latest
            ext: tar.gz
          - goos: windows
            goarch: amd64
            os: windows-latest
            ext: zip
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Get version
        id: package_version
        shell: bash
        run: |
          VERSION="$(go run ./cmd/lssh/ --version | awk '{print $NF}')"
          echo "::set-output name=version::$VERSION"

      - name: Build binary
        run: |
          go build -o lssh.${{ matrix.goos }}_${{ matrix.goarch }} ./cmd/lssh
          go build -o lscp.${{ matrix.goos }}_${{ matrix.goarch }} ./cmd/lscp
          go build -o lsftp.${{ matrix.goos }}_${{ matrix.goarch }} ./cmd/lsftp

      - name: Create package file
        if: ${{ (matrix.ext == 'tar.gz') || (matrix.ext == 'rpm') || (matrix.ext == 'deb') }}
        run: |
          _TAR=lssh_${{ steps.package_version.outputs.version }}_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz
          mkdir -p package/bin
          mv lssh.${{ matrix.goos }}_${{ matrix.goarch }} package/bin/lssh
          mv lscp.${{ matrix.goos }}_${{ matrix.goarch }} package/bin/lscp
          mv lsftp.${{ matrix.goos }}_${{ matrix.goarch }} package/bin/lsftp
          ## mkdir -p package/man
          ## cp man/lssh.1 package/man
          cp -r completion package/
          ## sed -i is not used due to difference between macOS and Linux
          perl -i -pe s/___VERSION___/${{ steps.package_version.outputs.version }}/ ./package/.tar2package.yml
          ## tar czvf "$_TAR" -C "$PWD/package" completion bin man .tar2package.yml
          tar czvf "$_TAR" -C "$PWD/package" completion bin .tar2package.yml

      - name: Create package file(Windows)
        if: matrix.ext == 'zip'
        run: |
          mkdir package/bin
          move lssh.${{ matrix.goos }}_${{ matrix.goarch }} package/bin/lssh
          move lscp.${{ matrix.goos }}_${{ matrix.goarch }} package/bin/lscp
          move lsftp.${{ matrix.goos }}_${{ matrix.goarch }} package/bin/lsftp
          powershell Compress-Archive package lssh_${{ steps.package_version.outputs.version }}_${{ matrix.goos }}_${{ matrix.goarch }}.zip


      - name: Upload artifact
        if: matrix.ext == 'tar.gz'
        uses: actions/upload-artifact@v1
        with:
          name: build-${{ matrix.goos }}_${{ matrix.goarch }}
          path: lssh_${{ steps.package_version.outputs.version }}_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz

      - name: Upload artifact
        if: matrix.ext == 'zip'
        uses: actions/upload-artifact@v1
        with:
          name: build-${{ matrix.goos }}_${{ matrix.goarch }}
          path: lssh_${{ steps.package_version.outputs.version }}_${{ matrix.goos }}_${{ matrix.goarch }}.zip
